### PR TITLE
Initial Stash support for PRs

### PR DESCRIPTION
**Pull request by jbeluch**
Not quite ready for merge (only PRs are working), but wanted to see if this is something you'd like contributed.

If so, I figure you'll have some ideas about how you want to handle the extra arguments necessary for stash. Currently just passing around kwargs everywhere but obviously that's not optimal.

Since stash is always (I think) hosted privately, we need a stash_hostname. Also, stash is organized by project then by repo, so there is a project_name argument as well.

Lastly, I changed github_username/password to drop the github_ part so it can be reused.

### CODE REVIEW

**Comment by justinabrahms** [comment]
I am very into this contribution. Thank you for submitting it. I'll spend some time this evening reviewing, but wanted to say THANK YOU!

**Comment by justinabrahms** [comment]
The initial looks pretty good.

I'd call your 'stash_url' a 'base_url' which will be necessary for things like github enterprise anyway.

Security note is well taken. See #75.

We'll need to introduce a dispatcher for "Oh, this is stash. Use this reporter, etc".

Solid PR though. :)

**Comment by jbeluch** [comment]
The security thing was a copy paste from elsewhere in your repo :)

As far as the dispatcher goes, how will we know which service is requested? The URLs won't necessarily give away that info.

Separate CLI flag/config option? positional arg? nested config file under a key 'stash' or 'github'?

**Comment by justinabrahms** [comment]
I'd just add another flag. --service=github/stash  with github as the default.

**Comment by justinabrahms** [comment]
Feel free to open when you're excited about it again.

**Pull request closed without merging**
