### PR TITLE
GitHub reporter no longer takes a repo name

### PR DESCRIPTION
**Pull request by danpalmer**
Fixes reporting to GitHub.

Note: I'm doing this all from the web interface, have not actually run the tests myself yet, hopefully Travis will tell me if it works.

### CODE REVIEW

**Comment by justinabrahms** [comment]
As the build was passing before, Travis won't tell you. This will actually need some changes to the test file to ensure that we're keeping true to the Reporter's API. I can make the changes this evening if you don't get to it first.

**Comment by danpalmer** [comment]
Thanks for sorting this, sorry I didn't get to it. Can you ping this when you've made a release to PyPI so that I can update our dependencies to use the main release rather than my branch? Thanks!

**Comment by justinabrahms** [comment]
Hey @danpalmer. I've release v1.0.1 to pypi. Are you guys using this at Torch? Somewhere else?

**Comment by danpalmer** [comment]
Yep, I just set it up today at Thread, we have Jenkins running Imhotep with the flake8 linter (and then a bunch of flake8 plugins for our style guide etc) running on PRs.

Thanks for the release and for being so responsive, I'll update our stuff.

**Comment by danpalmer** [comment]
Also thanks for open-sourcing Imhotep, particularly I like the fact that:

 - It's just a script we can run on Jenkins, no hosting a server, setting up new hooks, etc.
 - It just runs flake8 (in our case), we have existing configuration for flake8 linters, nice to have control over that which you often don't get in other services, they mix _linting infrastructure_ with _linting their way_.

**Comment by justinabrahms** [comment]
Thanks. If you ever want to use a hosted version at your company, I made one over at https://betterdiff.com/. If not, keep rocking on. I'd love to help with the open source side however I can.

**Comment by danpalmer** [comment]
@justinabrahms we'll certainly consider it, especially if this ends up taking too much time to maintain. For the moment though, I think we want to self-host, as we use a bunch of custom flake8 plugins, and I'm guessing you don't allow the use of custom plugins?

**Comment by justinabrahms** [comment]
Not yet. I'd like to and I've been considering some architecture wherein I
could run untrusted code.. but not yet sure on the direction there.

**Comment by danpalmer** [comment]
Yeah, that's the core of the problem isn't it, with just the linters, I guess nothing needs to be trusted, but if we provide the `requirements.txt` or something (because we use forks of linters, etc), that could cause issues.

**Pull request closed without merging**
